version: '3'

services:
    app:
        build:
            context: ./php
            dockerfile: Dockerfile
        image: microblog-app
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./../:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    db:
        image: postgres:13.5
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: postgres
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - app-network

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./../:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

volumes:
    dbdata:
        driver: local

networks:
    app-network:
        driver: bridge
